CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'officer',
  active INTEGER NOT NULL DEFAULT 1,
  subscription_start_at TIMESTAMPTZ,
  subscription_end_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  ktp TEXT UNIQUE,
  address TEXT,
  rt_rw TEXT,
  kel TEXT,
  kec TEXT,
  business TEXT,
  business_location TEXT,
  region TEXT,
  registration_no TEXT,
  owner_user_id INTEGER REFERENCES users(id),
  collection_day TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS savings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER REFERENCES members(id),
  date TIMESTAMPTZ NOT NULL,
  description TEXT,
  wajib INTEGER DEFAULT 0,
  khusus INTEGER DEFAULT 0,
  total INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS saving_withdrawals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER REFERENCES members(id),
  date TIMESTAMPTZ NOT NULL,
  description TEXT,
  amount INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS loans (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER REFERENCES members(id),
  loan_date TIMESTAMPTZ NOT NULL,
  amount INTEGER NOT NULL,
  admin_fee INTEGER DEFAULT 0,
  disbursed_amount INTEGER NOT NULL,
  installment_amount INTEGER NOT NULL,
  weeks INTEGER NOT NULL,
  total_to_pay INTEGER NOT NULL,
  status TEXT DEFAULT 'active'
);

CREATE TABLE IF NOT EXISTS loan_payments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id INTEGER REFERENCES loans(id),
  payment_date TIMESTAMPTZ NOT NULL,
  installment_no INTEGER NOT NULL,
  amount_paid INTEGER NOT NULL,
  remaining_balance INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_members_owner_user_id ON members(owner_user_id);
CREATE INDEX IF NOT EXISTS idx_savings_member_id_date ON savings(member_id, date);
CREATE INDEX IF NOT EXISTS idx_saving_withdrawals_member_id_date ON saving_withdrawals(member_id, date);
CREATE INDEX IF NOT EXISTS idx_loans_member_id_status ON loans(member_id, status);
CREATE INDEX IF NOT EXISTS idx_loan_payments_loan_id_payment_date ON loan_payments(loan_id, payment_date);
CREATE INDEX IF NOT EXISTS idx_sessions_user_id_expires_at ON sessions(user_id, expires_at);
